import type { MichelinItem } from '@/lib/michelin';

/**
 * Демо-доска «Мишлен» для Сеула: рестораны гида MICHELIN. Названия и кухня —
 * со скриншотов списка гида (предоставлены пользователем); отличие (звёзды /
 * Bib Gourmand) сверено с официальным списком гида, остальные — «Selected».
 * Координаты — геокодер Kakao (не найденные → coords:null: в списке есть, на
 * карте нет). Фикстура (как `mediaDemo`). СГЕНЕРИРОВАНО scripts/build_michelin.py.
 */
export const SEOUL_MICHELIN_DEMO: MichelinItem[] = [
  { id: 'mich_mingles', name: 'Mingles', coords: [37.52542, 127.044106], cuisine: 'Korean', distinction: 'star3', price: '₩₩₩₩', geo: 'Mingles Seoul' },
  { id: 'mich_alla-prima', name: 'Alla Prima', coords: [37.513538, 127.026027], cuisine: 'Innovative', distinction: 'star2', price: '₩₩₩₩', geo: 'Alla Prima Seoul' },
  { id: 'mich_evett', name: 'Evett', coords: [37.523383, 127.036234], cuisine: 'Innovative', distinction: 'star2', price: '₩₩₩₩', geo: 'Evett Seoul' },
  { id: 'mich_jungsik', name: 'Jungsik', coords: [37.525612, 127.041071], cuisine: 'Contemporary', distinction: 'star2', price: '₩₩₩₩', geo: 'Jungsik Seoul' },
  { id: 'mich_kwonsooksoo', name: 'Kwonsooksoo', coords: [37.524372, 127.043576], cuisine: 'Korean', distinction: 'star2', price: '₩₩₩₩', geo: 'Kwonsooksoo Seoul' },
  { id: 'mich_la-yeon', name: 'La Yeon', coords: [37.555897, 127.00517], cuisine: 'Korean', distinction: 'star2', price: '₩₩₩₩', geo: 'La Yeon Seoul' },
  { id: 'mich_mitou', name: 'Mitou', coords: [37.522119, 127.045046], cuisine: 'Japanese', distinction: 'star2', price: '₩₩₩₩', geo: 'Mitou Seoul' },
  { id: 'mich_mosu', name: 'Mosu', coords: [37.541197, 126.996181], cuisine: 'Modern Cuisine', distinction: 'star2', price: '₩₩₩₩', geo: 'Mosu Seoul' },
  { id: 'mich_soigne', name: 'Soigné', coords: null, cuisine: 'Contemporary', distinction: 'star2', price: '₩₩₩₩', geo: 'Soigné Seoul' },
  { id: 'mich_sosuheon', name: 'Sosuheon', coords: [37.557131, 126.968622], cuisine: 'Sushi', distinction: 'star2', price: '₩₩₩₩', geo: 'Sosuheon Seoul' },
  { id: 'mich_7th-door', name: '7th Door', coords: [37.522403, 127.054311], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: '7th Door Seoul' },
  { id: 'mich_collage', name: 'Collage', coords: [37.535368, 127.010061], cuisine: 'French Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Collage Seoul' },
  { id: 'mich_eatanic-garden', name: 'Eatanic Garden', coords: [37.502864, 127.041183], cuisine: 'Korean Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Eatanic Garden Seoul' },
  { id: 'mich_escondido', name: 'Escondido', coords: [37.535129, 127.010556], cuisine: 'Mexican', distinction: 'star1', price: '₩₩₩', geo: 'Escondido Seoul' },
  { id: 'mich_exquisine', name: 'Exquisine', coords: [37.521032, 127.049687], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Exquisine Seoul' },
  { id: 'mich_gagen-by-choi-junho', name: 'Gagen by Choi Junho', coords: [37.524502, 127.045245], cuisine: 'Japanese', distinction: 'star1', price: '₩₩₩', geo: 'Gagen by Choi Junho Seoul' },
  { id: 'mich_gigas', name: 'Gigas', coords: [37.556976, 126.978123], cuisine: 'Mediterranean Cuisine', distinction: 'star1', price: '₩₩₩', geo: 'Gigas Seoul' },
  { id: 'mich_giwakang', name: 'GiwaKang', coords: null, cuisine: 'Korean Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'GiwaKang Seoul' },
  { id: 'mich_goryori-ken', name: 'Goryori Ken', coords: [37.523009, 127.034806], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Goryori Ken Seoul' },
  { id: 'mich_hakushi', name: 'Hakushi', coords: [37.524113, 127.032287], cuisine: 'Japanese', distinction: 'star1', price: '₩₩₩', geo: 'Hakushi Seoul' },
  { id: 'mich_jueun', name: 'JUEUN', coords: [37.50368, 127.096826], cuisine: 'Korean', distinction: 'star1', price: '₩₩₩', geo: 'JUEUN Seoul' },
  { id: 'mich_kang-minchul-restaurant', name: 'Kang Minchul Restaurant', coords: [37.524966, 127.043682], cuisine: 'French Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Kang Minchul Restaurant Seoul' },
  { id: 'mich_l-amant-secret', name: 'L\'Amant Secret', coords: [37.559904, 126.979491], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'L\'Amant Secret Seoul' },
  { id: 'mich_l-amitie', name: 'L\'Amitié', coords: null, cuisine: 'French', distinction: 'star1', price: '₩₩₩', geo: 'L\'Amitié Seoul' },
  { id: 'mich_legume', name: 'Légume', coords: [37.519884, 127.019078], cuisine: 'Vegan', distinction: 'star1', price: '₩₩₩', geo: 'Légume Seoul' },
  { id: 'mich_muni', name: 'Muni', coords: [37.522948, 127.045485], cuisine: 'Japanese', distinction: 'star1', price: '₩₩₩', geo: 'Muni Seoul' },
  { id: 'mich_muoki', name: 'Muoki', coords: [37.51903, 127.042238], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Muoki Seoul' },
  { id: 'mich_onjium', name: 'Onjium', coords: [37.580495, 126.973391], cuisine: 'Korean', distinction: 'star1', price: '₩₩₩', geo: 'Onjium Seoul' },
  { id: 'mich_pierre-gagnaire', name: 'Pierre Gagnaire', coords: [37.565345, 126.980957], cuisine: 'French', distinction: 'star1', price: '₩₩₩', geo: 'Pierre Gagnaire Seoul' },
  { id: 'mich_san', name: 'SAN', coords: [37.569756, 126.904405], cuisine: 'Innovative', distinction: 'star1', price: '₩₩₩', geo: 'SAN Seoul' },
  { id: 'mich_solbam', name: 'Solbam', coords: [37.515715, 127.034005], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Solbam Seoul' },
  { id: 'mich_soseoul-hannam', name: 'Soseoul Hannam', coords: [37.535138, 127.009131], cuisine: 'Korean', distinction: 'star1', price: '₩₩₩', geo: 'Soseoul Hannam Seoul' },
  { id: 'mich_soul', name: 'Soul', coords: [37.488451, 127.014301], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Soul Seoul' },
  { id: 'mich_sushi-matsumoto', name: 'Sushi Matsumoto', coords: [37.525798, 127.04566], cuisine: 'Sushi', distinction: 'star1', price: '₩₩₩', geo: 'Sushi Matsumoto Seoul' },
  { id: 'mich_tutoiement', name: 'Tutoiement', coords: [37.549648, 127.06668], cuisine: 'French', distinction: 'star1', price: '₩₩₩', geo: 'Tutoiement Seoul' },
  { id: 'mich_vinho', name: 'VINHO', coords: [37.518597, 127.038115], cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'VINHO Seoul' },
  { id: 'mich_y-east', name: 'Y\'east', coords: null, cuisine: 'Contemporary', distinction: 'star1', price: '₩₩₩', geo: 'Y\'east Seoul' },
  { id: 'mich_yu-yuan', name: 'Yu Yuan', coords: [37.570422, 126.975578], cuisine: 'Chinese', distinction: 'star1', price: '₩₩₩', geo: 'Yu Yuan Seoul' },
  { id: 'mich_yun', name: 'YUN', coords: [37.469611, 127.03657], cuisine: 'Korean', distinction: 'star1', price: '₩₩₩', geo: 'YUN Seoul' },
  { id: 'mich_zero-complex', name: 'Zero Complex', coords: [37.520843, 126.992854], cuisine: 'Innovative', distinction: 'star1', price: '₩₩₩', geo: 'Zero Complex Seoul' },
  { id: 'mich_3rd-samgyetang', name: '3rd Samgyetang', coords: [37.491356, 127.011556], cuisine: 'Samgyetang', distinction: 'bib', price: '₩', geo: '3rd Samgyetang Seoul' },
  { id: 'mich_alt-a', name: 'ALT.a', coords: [37.532454, 126.994474], cuisine: 'Vegan', distinction: 'bib', price: '₩', geo: 'ALT.a Seoul' },
  { id: 'mich_anam', name: 'ANAM', coords: [37.587114, 127.026664], cuisine: 'Dwaeji-gukbap', distinction: 'bib', price: '₩', geo: 'ANAM Seoul' },
  { id: 'mich_andeok', name: 'Andeok', coords: [33.259897, 126.360927], cuisine: 'Korean', distinction: 'bib', price: '₩', geo: 'Andeok Seoul' },
  { id: 'mich_base-is-nice', name: 'Base is nice', coords: [37.539627, 126.949102], cuisine: 'Vegetarian', distinction: 'bib', price: '₩', geo: 'Base is nice Seoul' },
  { id: 'mich_daesungjip', name: 'Daesungjip', coords: null, cuisine: 'Doganitang', distinction: 'bib', price: '₩', geo: 'Daesungjip Seoul' },
  { id: 'mich_damtaek', name: 'Damtaek', coords: [37.554452, 126.915165], cuisine: 'Ramen', distinction: 'bib', price: '₩', geo: 'Damtaek Seoul' },
  { id: 'mich_gaeseong-mandu-koong', name: 'Gaeseong Mandu Koong', coords: [37.574284, 126.985392], cuisine: 'Mandu', distinction: 'bib', price: '₩', geo: 'Gaeseong Mandu Koong Seoul' },
  { id: 'mich_gebangsikdang', name: 'Gebangsikdang', coords: null, cuisine: 'Gejang', distinction: 'bib', price: '₩', geo: 'Gebangsikdang Seoul' },
  { id: 'mich_geumdwaeji-sikdang', name: 'Geumdwaeji Sikdang', coords: [37.557059, 127.01168], cuisine: 'Barbecue', distinction: 'bib', price: '₩', geo: 'Geumdwaeji Sikdang Seoul' },
  { id: 'mich_ggupdang', name: 'Ggupdang', coords: null, cuisine: 'Barbecue', distinction: 'bib', price: '₩', geo: 'Ggupdang Seoul' },
  { id: 'mich_gomtang-lab', name: 'Gomtang Lab', coords: [37.508615, 127.059763], cuisine: 'Gomtang', distinction: 'bib', price: '₩', geo: 'Gomtang Lab Seoul' },
  { id: 'mich_gosari-express', name: 'Gosari Express', coords: [37.566268, 127.020009], cuisine: 'Vegan', distinction: 'bib', price: '₩', geo: 'Gosari Express Seoul' },
  { id: 'mich_halmaejip', name: 'Halmaejip', coords: [37.586872, 126.917756], cuisine: 'Korean', distinction: 'bib', price: '₩', geo: 'Halmaejip Seoul' },
  { id: 'mich_hapjeongok', name: 'Hapjeongok', coords: [37.549534, 126.91051], cuisine: 'Gomtang', distinction: 'bib', price: '₩', geo: 'Hapjeongok Seoul' },
  { id: 'mich_horapa', name: 'HORAPA', coords: [37.579382, 126.971116], cuisine: 'Thai', distinction: 'bib', price: '₩', geo: 'HORAPA Seoul' },
  { id: 'mich_hwa-hae-dang', name: 'Hwa Hae Dang', coords: null, cuisine: 'Gejang', distinction: 'bib', price: '₩', geo: 'Hwa Hae Dang Seoul' },
  { id: 'mich_hwanggeum-kongbat', name: 'Hwanggeum Kongbat', coords: [37.550966, 126.956734], cuisine: 'Dubu', distinction: 'bib', price: '₩', geo: 'Hwanggeum Kongbat Seoul' },
  { id: 'mich_hwangsaengga-kalguksu', name: 'Hwangsaengga Kalguksu', coords: [37.58006, 126.980641], cuisine: 'Kalguksu', distinction: 'bib', price: '₩', geo: 'Hwangsaengga Kalguksu Seoul' },
  { id: 'mich_jaha-son-mandu', name: 'Jaha Son Mandu', coords: null, cuisine: 'Mandu', distinction: 'bib', price: '₩', geo: 'Jaha Son Mandu Seoul' },
  { id: 'mich_jeongmyeon', name: 'Jeongmyeon', coords: [37.545487, 127.068694], cuisine: 'Noodles', distinction: 'bib', price: '₩', geo: 'Jeongmyeon Seoul' },
  { id: 'mich_jin-jin', name: 'Jin Jin', coords: [37.485519, 127.120971], cuisine: 'Chinese', distinction: 'bib', price: '₩', geo: 'Jin Jin Seoul' },
  { id: 'mich_junjin-myeonok', name: 'Junjin Myeonok', coords: null, cuisine: 'Naengmyeon', distinction: 'bib', price: '₩', geo: 'Junjin Myeonok Seoul' },
  { id: 'mich_kyewol', name: 'Kyewol', coords: null, cuisine: 'Gomtang', distinction: 'bib', price: '₩', geo: 'Kyewol Seoul' },
  { id: 'mich_kyodaiya', name: 'Kyodaiya', coords: [37.546848, 126.91322], cuisine: 'Udon', distinction: 'bib', price: '₩', geo: 'Kyodaiya Seoul' },
  { id: 'mich_limbyungjoo-sandong-kalguksu', name: 'Limbyungjoo Sandong Kalguksu', coords: null, cuisine: 'Kalguksu', distinction: 'bib', price: '₩', geo: 'Limbyungjoo Sandong Kalguksu Seoul' },
  { id: 'mich_mandujip', name: 'Mandujip', coords: [37.530092, 127.122184], cuisine: 'Mandu', distinction: 'bib', price: '₩', geo: 'Mandujip Seoul' },
  { id: 'mich_mapo-ok', name: 'Mapo Ok', coords: [37.539882, 126.943338], cuisine: 'Seolleongtang', distinction: 'bib', price: '₩', geo: 'Mapo Ok Seoul' },
  { id: 'mich_mattdol', name: 'Mattdol', coords: [37.548311, 127.046744], cuisine: 'Mexican', distinction: 'bib', price: '₩', geo: 'Mattdol Seoul' },
  { id: 'mich_mijin', name: 'Mijin', coords: [37.570845, 126.979923], cuisine: 'Memil-guksu', distinction: 'bib', price: '₩', geo: 'Mijin Seoul' },
  { id: 'mich_mipildam', name: 'Mipildam', coords: [37.546618, 126.914211], cuisine: 'Mandu', distinction: 'bib', price: '₩', geo: 'Mipildam Seoul' },
  { id: 'mich_myeon-seoul', name: 'Myeon Seoul', coords: [37.524067, 127.03904], cuisine: 'Noodles', distinction: 'bib', price: '₩', geo: 'Myeon Seoul Seoul' },
  { id: 'mich_neungdong-minari', name: 'Neungdong Minari', coords: [37.551514, 127.090914], cuisine: 'Gomtang', distinction: 'bib', price: '₩', geo: 'Neungdong Minari Seoul' },
  { id: 'mich_nishimuramen', name: 'Nishimuramen', coords: null, cuisine: 'Ramen', distinction: 'bib', price: '₩', geo: 'Nishimuramen Seoul' },
  { id: 'mich_oilje', name: 'Oilje', coords: [37.53254, 126.974736], cuisine: 'Korean', distinction: 'bib', price: '₩', geo: 'Oilje Seoul' },
  { id: 'mich_okdongsik', name: 'Okdongsik', coords: [37.552677, 126.914521], cuisine: 'Dwaeji-gukbap', distinction: 'bib', price: '₩', geo: 'Okdongsik Seoul' },
  { id: 'mich_oreno-ramen', name: 'Oreno Ramen', coords: [37.576457, 126.984559], cuisine: 'Ramen', distinction: 'bib', price: '₩', geo: 'Oreno Ramen Seoul' },
  { id: 'mich_pildong-myeonok', name: 'Pildong Myeonok', coords: [37.560398, 126.99694], cuisine: 'Naengmyeon', distinction: 'bib', price: '₩', geo: 'Pildong Myeonok Seoul' },
  { id: 'mich_sarukame', name: 'Sarukame', coords: [37.561036, 126.922706], cuisine: 'Ramen', distinction: 'bib', price: '₩', geo: 'Sarukame Seoul' },
  { id: 'mich_seokyonanmyunbang', name: 'Seokyonanmyunbang', coords: null, cuisine: 'Noodles', distinction: 'bib', price: '₩', geo: 'Seokyonanmyunbang Seoul' },
  { id: 'mich_seoryung', name: 'Seoryung', coords: [37.5135, 127.104042], cuisine: 'Memil-guksu', distinction: 'bib', price: '₩', geo: 'Seoryung Seoul' },
  { id: 'mich_sobakeeri-suzu', name: 'Sobakeeri Suzu', coords: null, cuisine: 'Soba', distinction: 'bib', price: '₩', geo: 'Sobakeeri Suzu Seoul' },
  { id: 'mich_subaru', name: 'Subaru', coords: [37.492383, 126.986128], cuisine: 'Soba', distinction: 'bib', price: '₩', geo: 'Subaru Seoul' },
  { id: 'mich_woo-lae-oak', name: 'Woo Lae Oak', coords: [37.568071, 126.998742], cuisine: 'Naengmyeon', distinction: 'bib', price: '₩', geo: 'Woo Lae Oak Seoul' },
  { id: 'mich_yangyang-memil-makguksu', name: 'Yangyang Memil Makguksu', coords: [37.492516, 126.988285], cuisine: 'Memil-guksu', distinction: 'bib', price: '₩', geo: 'Yangyang Memil Makguksu Seoul' },
  { id: 'mich_yonggeumok', name: 'Yonggeumok', coords: [37.567662, 126.980508], cuisine: 'Chueotang', distinction: 'bib', price: '₩', geo: 'Yonggeumok Seoul' },
  { id: 'mich_youhan', name: 'Youhan', coords: [37.660941, 127.035167], cuisine: 'Thai', distinction: 'bib', price: '₩', geo: 'Youhan Seoul' },
  { id: 'mich_yukjeon-hoekwan', name: 'Yukjeon Hoekwan', coords: null, cuisine: 'Bulgogi', distinction: 'bib', price: '₩', geo: 'Yukjeon Hoekwan Seoul' },
  { id: 'mich_yurimmyeon', name: 'Yurimmyeon', coords: [35.51645, 127.728158], cuisine: 'Memil-guksu', distinction: 'bib', price: '₩', geo: 'Yurimmyeon Seoul' },
  { id: 'mich_a-l-aise', name: 'A L\'AISE', coords: null, cuisine: 'Modern Cuisine', distinction: 'plate', price: '₩₩', geo: 'A L\'AISE Seoul' },
  { id: 'mich_aelgerizm', name: 'Aelgerizm', coords: [37.523347, 127.037422], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Aelgerizm Seoul' },
  { id: 'mich_au-bouillon', name: 'Au Bouillon', coords: [37.550614, 127.026062], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Au Bouillon Seoul' },
  { id: 'mich_bistrot-de-yountville', name: 'Bistrot de Yountville', coords: [37.526078, 127.041242], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Bistrot de Yountville Seoul' },
  { id: 'mich_bium', name: 'Bium', coords: [37.522409, 127.054314], cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Bium Seoul' },
  { id: 'mich_bongmilga', name: 'Bongmilga', coords: [37.515981, 127.042405], cuisine: 'Naengmyeon', distinction: 'plate', price: '₩₩', geo: 'Bongmilga Seoul' },
  { id: 'mich_borgo-hannam', name: 'Borgo Hannam', coords: [37.537041, 127.00196], cuisine: 'Italian', distinction: 'plate', price: '₩₩', geo: 'Borgo Hannam Seoul' },
  { id: 'mich_born-and-bred', name: 'Born and Bred', coords: [37.566805, 127.04452], cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Born and Bred Seoul' },
  { id: 'mich_budnamujip', name: 'Budnamujip', coords: null, cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Budnamujip Seoul' },
  { id: 'mich_chaconne', name: 'Chaconne', coords: [37.502805, 127.033713], cuisine: 'French Contemporary', distinction: 'plate', price: '₩₩', geo: 'Chaconne Seoul' },
  { id: 'mich_chez-nous-private-kitchen', name: 'Chez Nous Private Kitchen', coords: [37.536345, 126.987396], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Chez Nous Private Kitchen Seoul' },
  { id: 'mich_chez-simon', name: 'Chez Simon', coords: [37.540084, 126.993845], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Chez Simon Seoul' },
  { id: 'mich_continental', name: 'Continental', coords: [37.556034, 127.005174], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Continental Seoul' },
  { id: 'mich_doori', name: 'Doori', coords: [37.53796, 126.963521], cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Doori Seoul' },
  { id: 'mich_doughroom', name: 'Doughroom', coords: [37.493825, 126.993346], cuisine: 'Italian', distinction: 'plate', price: '₩₩', geo: 'Doughroom Seoul' },
  { id: 'mich_egg-flour', name: 'Egg & Flour', coords: [37.545354, 126.984373], cuisine: 'Italian', distinction: 'plate', price: '₩₩', geo: 'Egg & Flour Seoul' },
  { id: 'mich_elpic', name: 'ELPIC', coords: [37.52235, 127.046607], cuisine: 'Meats and Grills', distinction: 'plate', price: '₩₩', geo: 'ELPIC Seoul' },
  { id: 'mich_gom-ba-wie', name: 'Gom Ba Wie', coords: null, cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Gom Ba Wie Seoul' },
  { id: 'mich_goobok-mandu', name: 'Goobok Mandu', coords: null, cuisine: 'Dim Sum', distinction: 'plate', price: '₩₩', geo: 'Goobok Mandu Seoul' },
  { id: 'mich_grandir', name: 'Grandir', coords: [37.527683, 127.039543], cuisine: 'French Contemporary', distinction: 'plate', price: '₩₩', geo: 'Grandir Seoul' },
  { id: 'mich_gucci-osteria-da-massimo-bottura', name: 'Gucci Osteria da Massimo Bottura', coords: [37.525069, 127.046526], cuisine: 'Italian Contemporary', distinction: 'plate', price: '₩₩', geo: 'Gucci Osteria da Massimo Bottura Seoul' },
  { id: 'mich_gwanghwamun-gukbap', name: 'Gwanghwamun Gukbap', coords: [37.568959, 126.975392], cuisine: 'Dwaeji-gukbap', distinction: 'plate', price: '₩₩', geo: 'Gwanghwamun Gukbap Seoul' },
  { id: 'mich_hadongkwan', name: 'Hadongkwan', coords: [37.562975, 126.985724], cuisine: 'Gomtang', distinction: 'plate', price: '₩₩', geo: 'Hadongkwan Seoul' },
  { id: 'mich_haenam-cheonilgwan', name: 'Haenam Cheonilgwan', coords: [37.512668, 127.101537], cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Haenam Cheonilgwan Seoul' },
  { id: 'mich_hane', name: 'HANE', coords: [37.527637, 127.034908], cuisine: 'Sushi', distinction: 'plate', price: '₩₩', geo: 'HANE Seoul' },
  { id: 'mich_haobin', name: 'Haobin', coords: [37.560145, 127.002249], cuisine: 'Chinese', distinction: 'plate', price: '₩₩', geo: 'Haobin Seoul' },
  { id: 'mich_il-vecchio', name: 'Il Vecchio', coords: [37.576377, 126.894702], cuisine: 'Italian', distinction: 'plate', price: '₩₩', geo: 'Il Vecchio Seoul' },
  { id: 'mich_imok-smoke-dining', name: 'Imok Smoke Dining', coords: [37.521148, 127.019308], cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Imok Smoke Dining Seoul' },
  { id: 'mich_imun-seolnongtang', name: 'Imun Seolnongtang', coords: [37.572734, 126.983908], cuisine: 'Seolleongtang', distinction: 'plate', price: '₩₩', geo: 'Imun Seolnongtang Seoul' },
  { id: 'mich_jinmi-pyeongyang-naengmyeon', name: 'Jinmi Pyeongyang Naengmyeon', coords: [37.516136, 127.036047], cuisine: 'Naengmyeon', distinction: 'plate', price: '₩₩', geo: 'Jinmi Pyeongyang Naengmyeon Seoul' },
  { id: 'mich_jinmi-sikdang', name: 'Jinmi Sikdang', coords: [37.550609, 126.955797], cuisine: 'Gejang', distinction: 'plate', price: '₩₩', geo: 'Jinmi Sikdang Seoul' },
  { id: 'mich_joo052', name: 'Joo052', coords: null, cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Joo052 Seoul' },
  { id: 'mich_jue', name: 'JUE', coords: [37.537473, 127.012808], cuisine: 'Chinese', distinction: 'plate', price: '₩₩', geo: 'JUE Seoul' },
  { id: 'mich_july', name: 'July', coords: [37.494719, 126.999989], cuisine: 'Modern Cuisine', distinction: 'plate', price: '₩₩', geo: 'July Seoul' },
  { id: 'mich_kirameki', name: 'Kirameki', coords: [37.518061, 127.028211], cuisine: 'Japanese', distinction: 'plate', price: '₩₩', geo: 'Kirameki Seoul' },
  { id: 'mich_kojacha', name: 'Kojacha', coords: [37.52088, 127.055203], cuisine: 'Asian', distinction: 'plate', price: '₩₩', geo: 'Kojacha Seoul' },
  { id: 'mich_kyoyang-siksa', name: 'Kyoyang Siksa', coords: null, cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Kyoyang Siksa Seoul' },
  { id: 'mich_l-oignon', name: 'L\'OIGNON', coords: null, cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'L\'OIGNON Seoul' },
  { id: 'mich_lee-buk-bang', name: 'Lee Buk Bang', coords: [37.689199, 127.884952], cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Lee Buk Bang Seoul' },
  { id: 'mich_manao', name: 'Manao', coords: [37.534097, 127.006178], cuisine: 'Thai', distinction: 'plate', price: '₩₩', geo: 'Manao Seoul' },
  { id: 'mich_mater', name: 'Mater', coords: [37.523285, 127.034648], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Mater Seoul' },
  { id: 'mich_mimi-myeonga', name: 'Mimi Myeonga', coords: [37.520053, 127.021104], cuisine: 'Noodles', distinction: 'plate', price: '₩₩', geo: 'Mimi Myeonga Seoul' },
  { id: 'mich_moulin', name: 'Moulin', coords: [37.581496, 126.971878], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Moulin Seoul' },
  { id: 'mich_mr-ahn-s-craft-makgeolli', name: 'Mr. Ahn\'s Craft Makgeolli', coords: null, cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Mr. Ahn\'s Craft Makgeolli Seoul' },
  { id: 'mich_mugunghwa', name: 'Mugunghwa', coords: [37.584221, 126.972407], cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Mugunghwa Seoul' },
  { id: 'mich_mukjung', name: 'Mukjung', coords: [37.561808, 127.000521], cuisine: 'Korean', distinction: 'plate', price: '₩₩', geo: 'Mukjung Seoul' },
  { id: 'mich_myeongdong-kyoja', name: 'Myeongdong Kyoja', coords: [37.561181, 126.986083], cuisine: 'Kalguksu', distinction: 'plate', price: '₩₩', geo: 'Myeongdong Kyoja Seoul' },
  { id: 'mich_myungbodang', name: 'Myungbodang', coords: [37.526132, 127.04149], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Myungbodang Seoul' },
  { id: 'mich_nampo-myeonok', name: 'Nampo Myeonok', coords: [37.567165, 126.981754], cuisine: 'Naengmyeon', distinction: 'plate', price: '₩₩', geo: 'Nampo Myeonok Seoul' },
  { id: 'mich_oegojip-seolleongtang', name: 'Oegojip Seolleongtang', coords: [37.511015, 127.053902], cuisine: 'Seolleongtang', distinction: 'plate', price: '₩₩', geo: 'Oegojip Seolleongtang Seoul' },
  { id: 'mich_on', name: 'ON', coords: [37.552317, 126.918948], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'ON Seoul' },
  { id: 'mich_one-degree-north', name: 'One Degree North', coords: [37.516706, 127.037447], cuisine: 'Asian', distinction: 'plate', price: '₩₩', geo: 'One Degree North Seoul' },
  { id: 'mich_onyva', name: 'Onyva', coords: [37.525193, 127.045718], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Onyva Seoul' },
  { id: 'mich_opnng', name: 'OPNNG', coords: [37.518892, 127.031018], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'OPNNG Seoul' },
  { id: 'mich_original-numbers', name: 'Original Numbers', coords: [37.525098, 127.040719], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Original Numbers Seoul' },
  { id: 'mich_osteria-orzo', name: 'Osteria Orzo', coords: [37.534885, 127.009493], cuisine: 'Italian', distinction: 'plate', price: '₩₩', geo: 'Osteria Orzo Seoul' },
  { id: 'mich_perigee', name: 'PERIGEE', coords: [37.511242, 127.049473], cuisine: 'Italian Contemporary', distinction: 'plate', price: '₩₩', geo: 'PERIGEE Seoul' },
  { id: 'mich_pyeongyang-myeonok', name: 'Pyeongyang Myeonok', coords: [37.563248, 127.006696], cuisine: 'Naengmyeon', distinction: 'plate', price: '₩₩', geo: 'Pyeongyang Myeonok Seoul' },
  { id: 'mich_restaurant-oy', name: 'Restaurant OY', coords: [37.522228, 127.043263], cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Restaurant OY Seoul' },
  { id: 'mich_rialto', name: 'Rialto', coords: [37.5232, 127.046528], cuisine: 'Italian', distinction: 'plate', price: '₩₩', geo: 'Rialto Seoul' },
  { id: 'mich_ryunique', name: 'Ryunique', coords: [37.522948, 127.036011], cuisine: 'Innovative', distinction: 'plate', price: '₩₩', geo: 'Ryunique Seoul' },
  { id: 'mich_samwon-garden', name: 'Samwon Garden', coords: [37.524826, 127.032643], cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Samwon Garden Seoul' },
  { id: 'mich_sanro', name: 'Sanro', coords: [37.524175, 127.049781], cuisine: 'Japanese', distinction: 'plate', price: '₩₩', geo: 'Sanro Seoul' },
  { id: 'mich_seoul-dining', name: 'Seoul Dining', coords: [37.565473, 126.829323], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Seoul Dining Seoul' },
  { id: 'mich_siio', name: 'SIIO', coords: [37.519548, 126.930491], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'SIIO Seoul' },
  { id: 'mich_sobajuu', name: 'Sobajuu', coords: null, cuisine: 'Japanese', distinction: 'plate', price: '₩₩', geo: 'Sobajuu Seoul' },
  { id: 'mich_sonnet', name: 'Sonnet', coords: [37.526293, 127.03705], cuisine: 'French Contemporary', distinction: 'plate', price: '₩₩', geo: 'Sonnet Seoul' },
  { id: 'mich_sooksoodoga', name: 'Sooksoodoga', coords: null, cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Sooksoodoga Seoul' },
  { id: 'mich_table-for-four', name: 'Table for Four', coords: [37.53466, 127.005238], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Table for Four Seoul' },
  { id: 'mich_the-green-table', name: 'The Green Table', coords: null, cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'The Green Table Seoul' },
  { id: 'mich_the-ninth-gate', name: 'The Ninth Gate', coords: null, cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'The Ninth Gate Seoul' },
  { id: 'mich_toc-toc', name: 'Toc Toc', coords: [37.522397, 127.054324], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Toc Toc Seoul' },
  { id: 'mich_toh-lim', name: 'Toh Lim', coords: [37.565338, 126.980962], cuisine: 'Chinese', distinction: 'plate', price: '₩₩', geo: 'Toh Lim Seoul' },
  { id: 'mich_trid', name: 'Trid', coords: [37.526706, 127.041688], cuisine: 'Contemporary', distinction: 'plate', price: '₩₩', geo: 'Trid Seoul' },
  { id: 'mich_yakitori-kiyu', name: 'Yakitori Kiyu', coords: null, cuisine: 'Yakitori', distinction: 'plate', price: '₩₩', geo: 'Yakitori Kiyu Seoul' },
  { id: 'mich_yakitori-mook', name: 'Yakitori Mook', coords: [37.564658, 126.924584], cuisine: 'Yakitori', distinction: 'plate', price: '₩₩', geo: 'Yakitori Mook Seoul' },
  { id: 'mich_yoon-haeundae-galbi', name: 'Yoon Haeundae Galbi', coords: null, cuisine: 'Barbecue', distinction: 'plate', price: '₩₩', geo: 'Yoon Haeundae Galbi Seoul' },
  { id: 'mich_zhonghuafuchun-salon', name: 'Zhonghuafuchun Salon', coords: null, cuisine: 'Chinese', distinction: 'plate', price: '₩₩', geo: 'Zhonghuafuchun Salon Seoul' },
  { id: 'mich_epanoui', name: 'Épanoui', coords: null, cuisine: 'French', distinction: 'plate', price: '₩₩', geo: 'Épanoui Seoul' },
];

const DEMO_CITIES = ['сеул', 'seoul'];

/** Демо-доска «Мишлен» для города из набора (Сеул), иначе пустой список. */
export function demoMichelinFor(city: string): MichelinItem[] {
  const c = (city || '').trim().toLowerCase();
  return DEMO_CITIES.some((d) => c.includes(d)) ? SEOUL_MICHELIN_DEMO : [];
}
